; This Django config file is baked into the image.
; It can override config settings in settings.py

[DEFAULT]
DEBUG               = False
LOG_LEVEL           = INFO
ALLOWED_HOSTS       = example.com
FRONTEND_URL        = https://example.com
FRONTEND_URL_EMAILS = https://example.com
FRONTEND_API_URL    = https://example.com/api
