# Generated by Django 5.2.1 on 2025-07-03 14:00

import django.db.models.deletion
import django.utils.timezone
import djultra.fields
import djultra.serializers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='transcript',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='all_thumbnails',
            field=djultra.fields.JSONField(blank=True, default=dict, encoder=djultra.serializers.CustomJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_id',
            field=djultra.fields.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_title',
            field=djultra.fields.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='default_audio_language_code',
            field=djultra.fields.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='default_caption_language_code',
            field=djultra.fields.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='duration_seconds',
            field=djultra.fields.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='raw_info',
            field=djultra.fields.JSONField(blank=True, default=dict, encoder=djultra.serializers.CustomJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='view_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=djultra.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=djultra.fields.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=djultra.fields.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='YouTubeTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', djultra.fields.CharField(blank=True, default='', max_length=2, null=True)),
                ('is_generated', models.BooleanField(default=True)),
                ('segments', djultra.fields.JSONField(blank=True, default=dict, encoder=djultra.serializers.CustomJSONEncoder, null=True)),
                ('text', djultra.fields.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='core.youtubevideo')),
            ],
            options={
                'ordering': ['video', 'language_code'],
                'unique_together': {('video', 'language_code')},
            },
        ),
    ]
