# Generated by Django 5.2.1 on 2025-07-04 12:41

import djultra.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_youtubevideo_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='status',
            field=djultra.fields.CharField(blank=True, choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('error', 'Error')], default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=djultra.fields.IntegerField(blank=True, null=True),
        ),
    ]
