# Generated by Django 5.2.1 on 2025-07-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_youtubevideo_status_alter_youtubevideo_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubetranscript',
            options={'ordering': ('video', 'language_code', 'is_generated')},
        ),
        migrations.AlterUniqueTogether(
            name='youtubetranscript',
            unique_together={('video', 'language_code', 'is_generated')},
        ),
    ]
